### PR TITLE
Fix for Execution failed for task ':react-native-exit-app:verifyReleaseResources'. #24

### PR DESCRIPTION
**Pull request by Samykills**
Fix fir #24 
https://github.com/wumke/react-native-exit-app/issues/24

updated Build.gradle(app) to use global project settings.

### CODE REVIEW

**Comment by wumke** [comment]
I'll test and merge this request, including @guhungry 's remark, in next release.
(I cannot say when I find the time to do this, just moved to a new house with a lot of work... that gets priority at the moment )

**Comment by Drvoldermort** [comment]
Still didn't get any solution for me.. Facing the same issue

**Comment by wumke** [comment]
As a temp fix you can always change the modifications yourself @Drvoldermort , then you can build for android...

**Comment by Samykills** [comment]
Awesome, thanks for merging :)

**Pull request merged**
