### PR TITLE
Delete react-native-exit-app.iml

### PR DESCRIPTION
**Pull request by SaeedZhiany**
This file is auto-generated (it can be generated every time you open android folder in android studio) and there is no need to commit this file in your repository.

### CODE REVIEW

**Comment by wumke** [comment]
I know (sometimes I delete these files on purpose when I have strange issues), don't really know why this did not end up in a gitignore file when I was creating this library :-)

Thanks

**Comment by SaeedZhiany** [comment]
It's because you have not `.gitignore` file in your project. I will create an initial one in another PR in a few minutes. (I didn't notice that when submitting this PR)

**Comment by SaeedZhiany** [comment]
with `*.iml` entry in the file, such files and other unnecessary file ignore to commit by Ideas and also git bash

**Comment by wumke** [comment]
Thanks, immediately merged it!

**Comment by SaeedZhiany** [comment]
you can review this PR to see if it's suitable for your project or not. if you think some of the entries are unnecessary for your project, tell me to remove them :)

**Pull request merged**
